### ISSUE TITLE
Bad Code style

### ISSUE THREAD

**Issue by samuelscheit** [xNaCly/better-issues#2]
Instead of manipulating the source code string:
```js
content = file_compact.toString().replace("&nbsp;SAMPLE_TITLE", `&nbsp;${title}`);
```
you should pass the data over with query parameters, e.g. ``file:///html/render.html?title=test``

If you need help you can reach me out on Discord: ``Flam3rboy#3490``

**Comment by xnacly** [comment]
currently working on it, thanks for the feedback

**Comment by xnacly** [comment]
Fixed in:
https://github.com/xNaCly/better-issues/commit/64a20ab494425aba41b995789c65d7c2dd97dcfb
https://github.com/xNaCly/better-issues/commit/29d95ce05caeeaadc0646bc94cefbd95e147f293

Thanks for the input
