### ISSUE TITLE
does this contains a dildo?

### ISSUE THREAD

**Issue by Intevel** [xNaCly/better-issues#4]
**dildo**
**dildo**

**dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo****dildo**

**Comment by xNaCly** [comment]
suck my cock retard
